### ISSUE TITLE
save demo-config policies in GitHub

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#114]
let's break this down to several smaller stories during a small scoping/ inception meeting.

**Comment by saurabh-io** [comment]
1. OPA Server config: https://github.com/hexa-org/policy-orchestrator/issues/282
2. Orchestrator backend: https://github.com/hexa-org/policy-orchestrator/issues/283
3. Add Provider UI: https://github.com/hexa-org/policy-orchestrator/issues/284

**Comment by saurabh-io** [comment]
Acceptance steps:

1. Create github repo (or use existing) and upload bundle.
2. Create a github personal access token with write:package, read:package permissions.
3. Pull latest from policy-orchestrator repo.
4. Build containers 
```policy-orchestrator]$ pack build hexa --builder heroku/buildpacks:20```
5. Export environment variables
```
export GITHUB_ACCOUNT="<YOUR_GITHUB_ORG_OR_ACCOUNT>"
export GITHUB_REPO="<REPO_NAME>"
export GITHUB_BRANCH="main"
export GITHUB_ACCESS_TOKEN="<GITHUB_PAT_FROM_STEP2>"

echo "GITHUB_ACCOUNT=${GITHUB_ACCOUNT} GITHUB_REPO=${GITHUB_REPO} GITHUB_BRANCH=${GITHUB_BRANCH} GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}"
```
6. Edit docker-compose.yml. In the opa-agent service replace `command` and `environment` with following
```
command: run --server --addr :8887 -c /home/config/github-opa-config.yaml
environment:
    GITHUB_ACCOUNT: "${GITHUB_ACCOUNT}"
    GITHUB_REPO: "${GITHUB_REPO}"
    GITHUB_BRANCH: "${GITHUB_BRANCH}"
    GITHUB_ACCESS_TOKEN: "${GITHUB_ACCESS_TOKEN}"
```
6. docker-compose up
7. On the admin UI, Create new OPA integration (sample integration json available on the UI).

**Comment by ggebel** [comment]
Updated acceptance steps:

1. Create github repo (or use existing) and upload bundle.
2. Create a github personal access token (classic) with write:package, read:package permissions.
3. Pull latest from policy-orchestrator repo.
4. Build containers
``` policy-orchestrator]$ pack build hexa --builder heroku/buildpacks:20 ```
5. Export environment variables
```
export GITHUB_ACCOUNT="<YOUR_GITHUB_ORG_OR_ACCOUNT>"
export GITHUB_REPO="<REPO_NAME>"
export GITHUB_BRANCH="main"
export GITHUB_ACCESS_TOKEN="<GITHUB_PAT_FROM_STEP2>"

echo "GITHUB_ACCOUNT=${GITHUB_ACCOUNT} GITHUB_REPO=${GITHUB_REPO} GITHUB_BRANCH=${GITHUB_BRANCH} GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}"
```
6. Edit docker-compose.yml. In the opa-agent service replace command and environment with following
```
command: run --server --addr :8887 -c /home/config/github-opa-config.yaml
environment:
    GITHUB_ACCOUNT: "${GITHUB_ACCOUNT}"
    GITHUB_REPO: "${GITHUB_REPO}"
    GITHUB_BRANCH: "${GITHUB_BRANCH}"
    GITHUB_ACCESS_TOKEN: "${GITHUB_ACCESS_TOKEN}"
```
7. Execute chmod commands
```
chmod 775 ./databases/docker_support/initdb.d/create-databases.sh
chmod 775 ./databases/docker_support/migrate-databases.sh
chmod 600 ./databases/docker_support/ca-cert.pem
chmod 600 ./databases/docker_support/client-cert.pem
chmod 600 ./databases/docker_support/client-key.pem
```
8. ```docker-compose up```
9. On the admin UI, Create new OPA integration (sample integration json available on the UI).
