### ISSUE TITLE
Orchestrator should support TLS

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#190]
this current happens in prod environments now. the only hesitation may be supporting a docker-compose environment locally. we should explore running tests via tls as well.

**Comment by barinek** [comment]
to test, update your `docker-compose.yml` file to include both server cert and key file per the below -
```
services:
  hexa-orchestrator:
      .
    environment:
      .
      SERVER_CERT: '/home/databases/docker_support/initdb.d/server-cert.pem'
      SERVER_KEY: '/home/databases/docker_support/initdb.d/server-key.pem'
```
next, include the root ca located `cmd/orchestrator/test/ca-cert.pem` in your local keychain
then for macs, you should be able to just double click the `ca-cert.pem` file
then, once registered, right-click and trust the certificate
restart docker
using your web browser, navigate to the orchestrator health endpoint `https://localhost:8885/health` and confirm the orchestrator is healthy
```
{"status":"pass"}
```
once complete, you can remove the root certificate from your keychain
